steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args: ['-c',
  'pip3 install -r release/requirements.txt && python3 release/release.py ${_BUILD_GCR} ${_RELEASE_GCR}'
  ]
