runtime: go114
instance_class: F2

env_variables:
  # Authentication variables
  COS_CHANGELOG_PROJECT_ID: "google.com:cos-changelog"  # Used to access project secrets from secret manager
  COS_CHANGELOG_OAUTH_CLIENT_ID_NAME: "cos-changelog-oauth-client-id"
  COS_CHANGELOG_CLIENT_SECRET_NAME: "cos-changelog-client-secret"
  COS_CHANGELOG_SESSION_SECRET_NAME: "cos-changelog-session-secret"
  COS_CHANGELOG_OAUTH_CALLBACK_NAME: "cos-changelog-oauth-callback"
  COS_CHANGELOG_ARTIFACTS_BUCKET_NAME: "cos-changelog-artifacts-bucket"

  # Webpage configuration
  STATIC_BASE_PATH: "src/cmd/changelog-webapp/static/"
  CHANGELOG_QUERY_SIZE: "50"
  BOARD_NAME: "lakitu"

  # External sources
  COS_EXTERNAL_GERRIT_INSTANCE: "https://cos-review.googlesource.com"
  COS_EXTERNAL_FALLBACK_GERRIT_INSTANCE: "https://chromium-review.googlesource.com"
  COS_EXTERNAL_GOB_INSTANCE: "cos.googlesource.com"
  COS_EXTERNAL_MANIFEST_REPO: "cos/manifest-snapshots"

  # Internal source names (values are retrieved from secret manager)
  COS_INTERNAL_GERRIT_INSTANCE_NAME: "cos-internal-gerrit-instance"
  COS_INTERNAL_FALLBACK_GERRIT_INSTANCE_NAME: "cos-internal-fallback-gerrit-instance"
  COS_INTERNAL_GOB_INSTANCE_NAME: "cos-internal-gob-instance"
  COS_INTERNAL_MANIFEST_REPO_NAME: "cos-internal-manifest-repo"
  CROSLAND_NAME: "crosland-url"
